import React from "react"
import { Poppins } from "next/font/google"

import StyledComponentsRegistry from "../lib/AntdRegistry"
import Navbar from "@/app/components/navbar/Navbar"

// import "@/globals.css"
import '@/app/globals.css'
import Footer from "./components/footer/Footer"

const poppins = Poppins({ weight:"400", subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

const RootLayout = ({ children }) => (
  <html lang="en">
    <body className={poppins.className}>
      <StyledComponentsRegistry>
        
 <Navbar/>

        {children}
 <Footer/>
        </StyledComponentsRegistry>
    </body>
  </html>
)

export default RootLayout
